apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: tauseefkhorajia/two-tier-flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service
         
        - name: MYSQL_USER
          value: admin

        - name: MYSQL_DB
          value: devops

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD  
         
        resources:
          requests:
            memory: 50Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 200m  
