apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: tauseefkhorajia/two-tier-flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: 
         
        - name: MYSQL_USER
          value: admin

        - name: mysql_database
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DB

        - name: mysql_password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD  


